from github_poller.parser import DiffParser


def test_parse_added_listing_realistic():
    diff_lines = [
        '@@ -18346,5 +18346,21 @@',
        '         "company_url": "https://simplify.jobs/c/Boeing",',
        '         "is_visible": true,',
        '+    },',
        '+    {',
        '+        "date_updated": 1754528498,',
        '+        "url": "https://careers-i3-corps.icims.com/jobs/4833/...",',
        '+        "company_name": "i3",',
        '+        "title": "Full-Stack Software Engineer",',
        '+        "locations": [',
        '+            "Huntsville, AL"',
        '+        ],',
        '+        "sponsorship": "U.S. Citizenship is Required",',
        '+        "active": true,',
        '+        "source": "AlmondCroffle",',
        '+        "id": "10757e82-0f1f-47cc-9dba-a04229089139",',
        '+        "date_posted": 1754528498,',
        '+        "company_url": "",',
        '+        "is_visible": true',
        '     }',  # context closing brace
        ' ]',  # context array closing
        '\\ No newline at end of file'
    ]
    listings = DiffParser.parse_added_listings(diff_lines)
    assert len(listings) == 1
    job = listings[0]
    assert job.company_name == "i3"
    assert job.id == "10757e82-0f1f-47cc-9dba-a04229089139"
    assert job.title == "Full-Stack Software Engineer"


def test_parse_added_and_deleted_listings_realistic():
    diff_lines = [
        # yapf: disable
        '@@ -517,22 +517,6 @@',
        '         "is_visible": true,',
        '         "sponsorship": "Other"',
        '     },',
        '-    {',
        '-        "source": "Simplify",',
        '-        "company_name": "Konrad Group",',
        '-        "id": "6baf7235-65ab-415c-b0e7-e982f11951e0",',
        '-        "title": "Software Developer \u2013 Entry Level",',
        '-        "active": false,',
        '-        "date_updated": 1723246690,',
        '-        "date_posted": 1723246690,',
        '-        "url": "https://boards.greenhouse.io/embed/job_app?token=6084188003",',
        '-        "locations": [',
        '-            "Remote in UK"',
        '-        ],',
        '-        "company_url": "https://simplify.jobs/c/Konrad-Group",',
        '-        "is_visible": true,',
        '-        "sponsorship": "Other"',
        '-    },',
        '     {',
        '         "source": "Simplify",',
        '         "company_name": "Pattern Data",',
        '@@ -549,22 +533,6 @@',
        '         "is_visible": true,',
        '         "sponsorship": "Other"',
        '     },',
        '-    {',
        '-        "source": "Simplify",',
        '-        "company_name": "Belvedere Trading",',
        '-        "id": "0c126d54-19b1-45cf-8655-3cc3bbfecde9",',
        '-        "title": "Quantitative Trader \u2013 Entry Level 2025",',
        '-        "active": false,',
        '-        "date_updated": 1723598087,',
        '-        "date_posted": 1723246982,',
        '-        "url": "https://jobs.lever.co/belvederetrading/69de6697-e9d4-426e-ae22-bad4c6e04cf8/apply",',
        '-        "locations": [',
        '-            "Chicago, IL"',
        '-        ],',
        '-        "company_url": "https://simplify.jobs/c/Belvedere-Trading",',
        '-        "is_visible": true,',
        '-        "sponsorship": "Other"',
        '-    },',
        '     {',
        '         "source": "Simplify",',
        '         "company_name": "Stripe",',
        '@@ -581,38 +549,6 @@',
        '         "is_visible": true,',
        '         "sponsorship": "Other"',
        '     },',
        '-    {',
        '-        "source": "Simplify",',
        '-        "company_name": "Konrad Group",',
        '-        "id": "3ef0f95b-7742-4447-a3de-44b0d83373fd",',
        '-        "title": "Mobile Developer \u2013 Entry Level",',
        '-        "active": false,',
        '-        "date_updated": 1723246687,',
        '-        "date_posted": 1723246687,',
        '-        "url": "https://boards.greenhouse.io/embed/job_app?token=6084310003",',
        '-        "locations": [',
        '-            "Remote in UK"',
        '-        ],',
        '-        "company_url": "https://simplify.jobs/c/Konrad-Group",',
        '-        "is_visible": true,',
        '-        "sponsorship": "Other"',
        '-    },',
        '-    {',
        '-        "source": "Simplify",',
        '-        "company_name": "Belvedere Trading",',
        '-        "id": "6c6dfa90-d789-473d-972e-f82f3b874d81",',
        '-        "title": "Software Engineer \u2013 Entry Level 2025",',
        '-        "active": false,',
        '-        "date_updated": 1723597767,',
        '-        "date_posted": 1723246712,',
        '-        "url": "https://jobs.lever.co/belvederetrading/f994033f-80f7-4f1d-afdf-a0ada8ed9a8b/apply",',
        '-        "locations": [',
        '-            "Chicago, IL"',
        '-        ],',
        '-        "company_url": "https://simplify.jobs/c/Belvedere-Trading",',
        '-        "is_visible": true,',
        '-        "sponsorship": "Other"',
        '-    },',
        '     {',
        '         "source": "Simplify",',
        '         "company_name": "Applied Intuition",',
        '@@ -17840,5 +17776,22 @@',
        '         "date_posted": 1754344367,',
        '         "company_url": "",',
        '         "is_visible": true',
        '+    },',
        '+    {',
        '+        "source": "Simplify",',
        '+        "category": "Software",',
        '+        "company_name": "Zoro",',
        '+        "id": "e825cd57-2482-4e89-b28a-901424d7269b",',
        '+        "title": "Software Engineer I - Release Platform",',
        '+        "active": true,',
        '+        "date_updated": 1754351086,',
        '+        "date_posted": 1754351086,',
        '+        "url": "https://zoro.com/careers/jobs?gh_jid=4589860006",',
        '+        "locations": [',
        '+            "Chicago, IL"',
        '+        ],',
        '+        "company_url": "https://simplify.jobs/c/Zoro",',
        '+        "is_visible": true,',
        '+        "sponsorship": "Other"',
        '     }',
        ' ]',
        '\\ No newline at end of file'
        # yapf: enable
    ]
    listings = DiffParser.parse_added_listings(diff_lines)
    assert len(listings) == 1
    job = listings[0]
    assert job.company_name == "Zoro"
    assert job.id == "e825cd57-2482-4e89-b28a-901424d7269b"
    assert job.title == "Software Engineer I - Release Platform"
